# Generated by Django 4.1.7 on 2023-02-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='_name',
            new_name='name',
        ),
    ]
