# Generated by Django 4.1.7 on 2023-02-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='addres',
            new_name='address',
        ),
    ]
