# Generated by Django 4.1.7 on 2023-02-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0002_rename_addres_place_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='number',
            new_name='number_employees',
        ),
    ]
